version: '3.9'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  node_modules: {}